DECLARE
--    V_CUST_ID CUSTOMER.CUST_ID%TYPE;
--    V_CUST_NAME CUSTOMER.CU_NAME%TYPE;
--    V_TEL CUSTOMER.TLE%TYPE;
--    V_ADDR CUSTOMER.ADDR%TYPE;
    V_CUSTROW CUSTOMER%ROWTYPE;
BEGIN
    SELECT *
--        INTO V_CUST_ID, V_CUST_NAME, V_TEL, V_ADDR
        INTO V_CUSTROW
    FROM CUSTOMER
    WHERE CUST_ID = '10001';
--    DBMS_OUTPUT.PUT_LINE(V_CUST_ID || V_CUST_NAME || V_TEL || V_ADDR);
    DBMS_OUTPUT.PUT_LINE(V_CUSTROW.CUST_ID);
    DBMS_OUTPUT.PUT_LINE(V_CUSTROW.CU_NAME);
    DBMS_OUTPUT.PUT_LINE(V_CUSTROW.TEL);
    DBMS_OUTPUT.PUT_LINE(V_CUSTROW.ADDR);
END;