declare
V_DEPTNO DEPT.DEPTNO%TYPE;
V_DNAME DEPT.DNAME%TYPE;
V_LOC DEPT.LOC%TYPE;
CURSOR DEPT_CUR IS
    SELECT * FROM DEPT;
BEGIN
OPEN DEPT_CUR;
LOOP
    FETCH DEPT_CUR INTO V_DEPTNO, V_DNAME, V_LOC;
    EXIT WHEN DEPT_CUR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('부서번호 : ' || V_DEPTNO || 
                        '부서명 : ' || V_DNAME ||
                        '위치 : ' || V_LOC);
END LOOP;
END;

DECLARE
    V_DEPT_ROW DEPT%ROWTYPE;
    V_DEPTNO DEPT.DEPTNO%TYPE;
    
    CURSOR C1(P_DEPTNO DEPT.DEPTNO%TYPE) IS
    SELECT * FROM DEPT
    WHERE DEPTNO = P_DEPTNO;
    
BEGIN
    V_DEPTNO := &INPUT_DEPTNO;
    OPEN C1(V_DEPTNO);
    LOOP
        FETCH C1 INTO V_DEPT_ROW;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_DEPTNO || '번 부서' || V_DEPT_ROW.DNAME || ', ' ||
                                V_DEPT_ROW.LOC);
    END LOOP;
    CLOSE C1;
    
    OPEN C1(30);
    LOOP
        FETCH C1 INTO V_DEPT_ROW;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('30번 부서' || V_DEPT_ROW.DNAME || ', ' ||
                                V_DEPT_ROW.LOC);
    END LOOP;
    CLOSE C1;
EXCEPTION
WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('부서번호 입력이 잘못 되었습ㄴ디ㅏ.');
END;

DECLARE
    V_WRONG NUMBER;
BEGIN
    SELECT DNAME INTO V_WRONG
    FROM DEPT
    WHERE DEPTNO =10;
    
    EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('예외처리 : 사전 정의외 오류');
END;
    


