CREATE OR REPLACE PROCEDURE EMP_SELECT(V_EMPNO IN NUMBER)
IS
    V_EMP_ROW EMP%ROWTYPE;
BEGIN
    SELECT * INTO V_EMP_ROW
    FROM EMP
    WHERE EMPNO = V_EMPNO;
    DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.EMPNO);
    DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.ENAME);
    DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.JOB);
    DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.MGR);
    DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.HIREDATE);
    DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.COMM);
    DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.DEPTNO);
END;


    
    
    
    