SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--부서번호가 30, 50, 60 이면서 SALARY가 10000이상인 사원의 사원번호, 이름,
--부서명, SALARY, 입사일을 조회 SQL문을 작성하시오.
SELECT EMPLOYEE_ID, FIRST_NAME || '' || LAST_NAME NAME, DEPARTMENT_NAME,
       SALARY, HIRE_DATE
FROM EMPLOYEES E, DEPARTMENTS D;
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.DEPARTMENT_ID IN(30,50,60);

SELECT EMPLOYEE_ID, FIRST_NAME || '' || LAST_NAME NAME, DEPARTMENT_NAME,
       SALARY, HIRE_DATE, CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
      AND D.LOCATION_ID=L.LOCATION_ID
      AND E.DEPARTMENT_ID IN(30,50,60);
      
--유럽에서 근무하는 사원의 사원번호, 이름, 부서명, 급여 정보를 조회하는 SQL문
SELECT EMPLOYEE_ID, FIRST_NAME || '' || LAST_NAME NAME, DEPARTMENT_NAME, SALARY
FROM EMPLOYEES E, DEPARTMENTS D, COUNTRIES C, LOCATIONS L, REGIONS R
WHERE R.REGION_NAME = 'Europe' AND
e.department_id=d.department_id AND
d.location_id=l.location_id AND
l.country_id=c.country_id AND
c.region_id=r.region_id;

--사원의 사원번호, 이름, 부서명, 급여, JOB_TITLE 조회하는 SQL문
SELECT EMPLOYEE_ID, FIRST_NAME || '' || LAST_NAME NAME, DEPARTMENT_NAME, SALARY, JOB_TITLE
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE J.JOB_ID=E.JOB_ID;

--4번
SELECT EMPLOYEE_ID, FIRST_NAME || '' || LAST_NAME NAME, J.JOB_ID, SALARY
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE SALARY>=2000 AND
      J.JOB_ID='ST_CLERK' AND
      J.JOB_ID=E.JOB_ID;
      
--8번
SELECT FIRST_NAME || '' || LAST_NAME NAME, 
      