SELECT * FROM EMPLOYEES;
-- SELECT 문 형식
--SELECT (DISTINCT) 테이블명.컬럼명1, 테이블명.컬럼명2, .....  : 조회할 컬럼들 (* : 모든 컬럼), 테이블명은 생략이 가능하다., DISTINCT : 중복데이터삭제
--FROM 테이블명1, 테이블명2,.....
--WHERE 조건
--GROUP BY 그룹화할 컬럼명
--HAVING 그룹화 테이터 조건
--ORDER BY (ASC/DESC) 순서지전 컬럼명 ASC:오름차순, DESC:내림차순

--월급이 10000불 이상인 사원의 사원번호, 이름, 월급, 부서번호를 조회
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY >= 10000;

--부서번호별 인원수조회
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

--부서번호별 인원수가 10명 이상인 부서 조회
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>=10
ORDER BY DEPARTMENT_ID;


SELECT * FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;

--별칭
SELECT Employee_Id AS 번호, FIRST_NAME AS 이름, SALARY AS 월급, SALARY*12 AS 연봉
FROM EMPLOYEES;

--AS는 생략이 가능하다.
SELECT Employee_Id 번호, FIRST_NAME 이름, SALARY 월급, SALARY*12 연봉
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENTS.DEPARTMENT_ID , DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, D.DEPARTMENT_ID , DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--문자열을 더할때는 ||연산자를 사용한다.
SELECT FIRST_NAME || ' ' || LAST_NAME "이름"
FROM EMPLOYEES;

--사원의 이름과 월급을 월급이 많은 순으로 조회
SELECT FIRST_NAME || ' ' || LAST_NAME "이름", SALARY 월급
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC, SALARY ASC;
